name: Build docs and npm publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          ACTION_CONTEXT: |
            {
              "env": ${{ toJSON(env) }},
              "github": ${{ toJSON(github) }},
              "inputs": ${{ toJSON(inputs) }},
              "job": ${{ toJSON(job) }},
              "runner": ${{ toJSON(runner) }},
              "secrets": ${{ toJSON(secrets) }},
              "steps": ${{ toJSON(steps) }},
              "vars": ${{ toJSON(vars) }}
            }
        run: echo "$ACTION_CONTEXT" | jq .
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: 'yarn'
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - name: install, lint, test, build
        run: |
          set -ex
          yarn
          yarn lint
          yarn test:ci
          yarn build
          yarn publish:test
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          ACTION_CONTEXT: |
            {
              "env": ${{ toJSON(env) }},
              "github": ${{ toJSON(github) }},
              "inputs": ${{ toJSON(inputs) }},
              "job": ${{ toJSON(job) }},
              "runner": ${{ toJSON(runner) }},
              "secrets": ${{ toJSON(secrets) }},
              "steps": ${{ toJSON(steps) }},
              "vars": ${{ toJSON(vars) }}
            }
        run: echo "$ACTION_CONTEXT" | jq .
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: 'yarn'
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - name: install and build
        run: |
          set -ex
          yarn
          yarn test:ci
          yarn build
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: 發布至 npm
        uses: JS-DevTools/npm-publish@v4
        id: npm-publish
        with:
          access: public
      - name: jsDelivr Purge
        uses: egad13/purge-jsdelivr-cache@v1
        if: ${{ steps.npm-publish.outputs.type }}
        with:
          url: |
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/index.global.js
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/Crypto1.global.js
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/plugin/DfuZip.global.js
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/plugin/SerialPortAdapter.global.js
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/plugin/WebbleAdapter.global.js
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/plugin/WebserialAdapter.global.js

            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/Crypto1/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/Crypto1.mjs/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/index.mjs/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/plugin/DfuZip.mjs/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/plugin/SerialPortAdapter.mjs/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/plugin/WebbleAdapter.mjs/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/dist/plugin/WebserialAdapter.mjs/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/plugin/DfuZip/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/plugin/SerialPortAdapter/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/plugin/WebbleAdapter/+esm
            https://cdn.jsdelivr.net/npm/chameleon-ultra.js@0/plugin/WebserialAdapter/+esm
